name: 'Create an Organization Repository'
description: 'Creates an Organization Repository and adds the Actor as an admin'
inputs:
  repo-name:  # change this as needed
    description: 'What is the name of the repository?'
    required: true
    default: ''
outputs:
  repo-url: # change this as needed
    description: 'URL of the created repository'
runs:
  using: 'node12'
  main: 'dist/index.js'