name: The local job
on: [workflow_dispatch]

jobs:
  local_job:
    runs-on: ubuntu-latest
    name: Run the local Action present in this repository
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          repo-name: 'Mona the Octocat'
      # Use the output from the `hello` step
